name: Build Dockerfile

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build image

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                username: ${{ github.actor }}
                password: ${{ secrets.GH_TOKEN }}
                registry: ghcr.io

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: ghcr.io/${{ github.repository }}/calculate:latest